global using System.Reflection;
global using BepInEx;
global using BepInEx.Configuration;
global using HarmonyLib;
global using UnityEngine;
global using System.Runtime.InteropServices;
global using System;
global using System.Collections.Generic;
global using System.Reflection.Emit;
global using Jotunn.Extensions;
global using System.IO;
global using System.IO.Compression;
global using VBNetTweaks.Utils;
global using System.Diagnostics;
global using Debug = UnityEngine.Debug;
global using System.Collections;
global using Jotunn.Entities;
global using Jotunn.Managers;
global using Jotunn.Utils;
global using Paths = BepInEx.Paths;
global using Steamworks;
global using VBNetTweaks.Patches;
global using VBNetTweaks.CompressionUtills;
global using VBNetTweaks.ZDOUtills;